//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlgorithmsTests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AlgorithmsTests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1
        ///1
        ///2
        ///3
        ///5
        ///8
        ///13
        ///21
        ///34
        ///55
        ///89
        ///144
        ///233
        ///377
        ///610
        ///987
        ///1597
        ///2584
        ///4181
        ///6765
        ///10946
        ///17711
        ///28657
        ///46368
        ///75025
        ///121393
        ///196418
        ///317811
        ///514229
        ///832040
        ///1346269
        ///2178309
        ///3524578
        ///5702887
        ///9227465
        ///14930352
        ///24157817
        ///39088169
        ///63245986
        ///102334155
        ///165580141
        ///267914296
        ///433494437
        ///701408733
        ///1134903170
        ///1836311903
        ///2971215073
        ///4807526976
        ///7778742049
        ///12586269025
        ///20365011074
        ///32951280099
        ///53316291173
        ///86267571272
        ///139583862445
        ///225851433717
        ///365435296162
        ///591286729879
        ///956722026041
        ///1548008755920
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Fibonacci {
            get {
                return ResourceManager.GetString("Fibonacci", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3,3,3,5,5,6,8,9,10,11,14,15,15,16,16,18,19,19,20,21,25,26,26,26,27,29,31,32,33,33,34,37,38,38,38,39,40,42,42,45,46,46,47,47,51,51,52,54,56,57,57,57,59,60,63,63,64,65,65,66,67,67,68,68,70,72,72,73,74,75,76,81,83,83,84,85,87,89,91,93,95,96,98,98,98,99,100,100,100,100,100,103,104,104,104,105,107,108,108,109,110,110,111,111,113,116,117,118,118,120,120,120,120,122,123,123,123,125,126,126,127,129,132,133,134,134,134,135,135,136,136,137,137,140,140,141,141,141,145,145,146,147,147,148,151,152,153,153,155,155,156,15 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string sorted {
            get {
                return ResourceManager.GetString("sorted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9299,1941,4653,8425,5235,5839,1499,2711,7617,6800,4298,489,8092,6655,2629,6637,597,1771,7617,9179,3315,9585,7416,6351,6021,4779,676,4590,268,4485,322,3554,5050,6853,9881,9953,3295,2463,573,9067,2741,8954,857,8526,8722,7242,9738,7925,4879,3026,4390,4719,8305,9801,9694,2324,4228,9349,5650,7407,4885,5900,2512,8622,8669,1183,1397,9986,8019,5483,7962,4402,4310,2482,2186,3439,1873,8374,6343,7177,5253,8561,8024,9014,1311,5,8327,9280,8161,3882,8208,2957,4331,5361,351,811,5123,5770,3139,2854,1529,8734,9050,8146,8464 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string unsorted {
            get {
                return ResourceManager.GetString("unsorted", resourceCulture);
            }
        }
    }
}
