//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlgorithmsTests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AlgorithmsTests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1
        ///1
        ///2
        ///3
        ///5
        ///8
        ///13
        ///21
        ///34
        ///55
        ///89
        ///144
        ///233
        ///377
        ///610
        ///987
        ///1597
        ///2584
        ///4181
        ///6765
        ///10946
        ///17711
        ///28657
        ///46368
        ///75025
        ///121393
        ///196418
        ///317811
        ///514229
        ///832040
        ///1346269
        ///2178309
        ///3524578
        ///5702887
        ///9227465
        ///14930352
        ///24157817
        ///39088169
        ///63245986
        ///102334155
        ///165580141
        ///267914296
        ///433494437
        ///701408733
        ///1134903170
        ///1836311903
        ///2971215073
        ///4807526976
        ///7778742049
        ///12586269025
        ///20365011074
        ///32951280099
        ///53316291173
        ///86267571272
        ///139583862445
        ///225851433717
        ///365435296162
        ///591286729879
        ///956722026041
        ///1548008755920
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FIBONACCI {
            get {
                return ResourceManager.GetString("FIBONACCI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 135896
        ///590992
        ///754778
        ///900472
        ///840273
        ///907422
        ///617307
        ///550028
        ///749175
        ///997514
        ///923377
        ///796872
        ///275349
        ///645116
        ///880119
        ///390648
        ///913852
        ///927963
        ///950545
        ///580101
        ///486698
        ///830602
        ///897573
        ///422220
        ///430213
        ///707866
        ///677219
        ///22878
        ///649763
        ///780514
        ///473614
        ///619949
        ///387879
        ///158923
        ///614962
        ///592998
        ///389002
        ///68858
        ///673824
        ///212757
        ///420380
        ///903441
        ///960500
        ///48247
        ///903186
        ///778022
        ///440244
        ///467319
        ///630928
        ///327132
        ///404675
        ///345535
        ///826283
        ///377968
        ///27818
        ///305294
        ///693418
        ///332558
        ///470259
        ///132406
        ///230203
        ///594428
        ///900264
        ///968660
        ///5238 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NUMS_MILLION {
            get {
                return ResourceManager.GetString("NUMS_MILLION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2
        ///3
        ///5
        ///6
        ///6
        ///7
        ///8
        ///8
        ///8
        ///10
        ///11
        ///11
        ///11
        ///15
        ///16
        ///17
        ///17
        ///17
        ///18
        ///18
        ///19
        ///19
        ///22
        ///22
        ///22
        ///22
        ///23
        ///24
        ///25
        ///27
        ///27
        ///27
        ///28
        ///29
        ///30
        ///31
        ///32
        ///33
        ///34
        ///34
        ///37
        ///39
        ///39
        ///40
        ///41
        ///44
        ///44
        ///45
        ///47
        ///48
        ///48
        ///49
        ///49
        ///50
        ///55
        ///55
        ///55
        ///55
        ///56
        ///57
        ///57
        ///58
        ///60
        ///61
        ///62
        ///64
        ///64
        ///64
        ///65
        ///65
        ///65
        ///66
        ///67
        ///67
        ///68
        ///68
        ///68
        ///69
        ///69
        ///71
        ///75
        ///77
        ///78
        ///79
        ///80
        ///81
        ///82
        ///82
        ///83
        ///83
        ///84
        ///87
        ///88
        ///91
        ///91
        ///92
        ///93
        ///95
        ///100
        ///102
        ///102
        ///103
        ///104
        ///104
        ///106
        ///106
        ///106
        ///106
        ///110
        ///111
        ///111
        ///115
        ///115
        ///116
        ///116
        ///116
        ///117
        ///117
        ///120
        ///121
        ///122
        ///122
        ///122
        ///124        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NUMS_MILLION_SORTED {
            get {
                return ResourceManager.GetString("NUMS_MILLION_SORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 999999
        ///999999
        ///999997
        ///999995
        ///999993
        ///999991
        ///999991
        ///999990
        ///999990
        ///999987
        ///999986
        ///999986
        ///999985
        ///999984
        ///999984
        ///999984
        ///999983
        ///999982
        ///999979
        ///999979
        ///999977
        ///999975
        ///999974
        ///999973
        ///999970
        ///999970
        ///999969
        ///999967
        ///999966
        ///999965
        ///999964
        ///999963
        ///999963
        ///999963
        ///999963
        ///999959
        ///999958
        ///999956
        ///999956
        ///999952
        ///999950
        ///999950
        ///999950
        ///999947
        ///999945
        ///999943
        ///999943
        ///999941
        ///999941
        ///999941
        ///999939
        ///999938
        ///999938
        ///999937
        ///999937
        ///999937
        ///999937
        ///999937
        ///999936
        ///999933
        ///999933
        ///999932
        ///999928
        ///999928
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NUMS_MILLION_SORTED_REVERSE {
            get {
                return ResourceManager.GetString("NUMS_MILLION_SORTED_REVERSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 25042
        ///10620
        ///15344
        ///9318
        ///9730
        ///20381
        ///22986
        ///565
        ///32229
        ///21225
        ///18330
        ///26500
        ///17928
        ///19956
        ///21995
        ///19511
        ///19203
        ///15537
        ///7484
        ///23232
        ///1902
        ///30106
        ///26546
        ///2230
        ///5716
        ///3403
        ///30632
        ///15463
        ///19298
        ///18925
        ///2306
        ///26023
        ///15558
        ///8018
        ///32250
        ///18138
        ///8453
        ///21163
        ///27169
        ///23127
        ///9525
        ///24992
        ///27699
        ///9116
        ///28466
        ///19068
        ///4955
        ///17618
        ///30797
        ///4775
        ///14531
        ///9627
        ///3635
        ///29882
        ///3538
        ///30258
        ///28453
        ///29449
        ///31334
        ///23897
        ///12256
        ///22476
        ///13320
        ///14340
        ///15873
        ///21391
        ///28464
        ///20017
        ///4138
        ///27189
        ///24881
        ///5958
        ///31400
        ///13803
        ///22500
        ///30394
        ///2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NUMS_TEN_MILLION {
            get {
                return ResourceManager.GetString("NUMS_TEN_MILLION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NUMS_TEN_MILLION_SORTED {
            get {
                return ResourceManager.GetString("NUMS_TEN_MILLION_SORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 32767
        ///32767
        ///32767
        ///32767
        ///32767
        ///32767
        ///32767
        ///32767
        ///32767
        ///32767
        ///32767
        ///32767
        ///32767
        ///32767
        ///32767
        ///32767
        ///32767
        ///32767
        ///32767
        ///32767
        ///32767
        ///32767
        ///32767
        ///32767
        ///32767
        ///32767
        ///32767
        ///32767
        ///32767
        ///32767
        ///32767
        ///32767
        ///32767
        ///32767
        ///32767
        ///32767
        ///32767
        ///32767
        ///32767
        ///32767
        ///32767
        ///32767
        ///32767
        ///32767
        ///32767
        ///32767
        ///32767
        ///32767
        ///32767
        ///32767
        ///32767
        ///32767
        ///32767
        ///32767
        ///32767
        ///32767
        ///32767
        ///32767
        ///32767
        ///32767
        ///32767
        ///32767
        ///32767
        ///32767
        ///32767
        ///32767
        ///32767
        ///32767
        ///32767
        ///32767
        ///32767
        ///32767
        ///32767
        ///3 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NUMS_TEN_MILLION_SORTED_REVERSE {
            get {
                return ResourceManager.GetString("NUMS_TEN_MILLION_SORTED_REVERSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9299
        ///1941
        ///4653
        ///8425
        ///5235
        ///5839
        ///1499
        ///2711
        ///7617
        ///6800
        ///4298
        ///489
        ///8092
        ///6655
        ///2629
        ///6637
        ///597
        ///1771
        ///7617
        ///9179
        ///3315
        ///9585
        ///7416
        ///6351
        ///6021
        ///4779
        ///676
        ///4590
        ///268
        ///4485
        ///322
        ///3554
        ///5050
        ///6853
        ///9881
        ///9953
        ///3295
        ///2463
        ///573
        ///9067
        ///2741
        ///8954
        ///857
        ///8526
        ///8722
        ///7242
        ///9738
        ///7925
        ///4879
        ///3026
        ///4390
        ///4719
        ///8305
        ///9801
        ///9694
        ///2324
        ///4228
        ///9349
        ///5650
        ///7407
        ///4885
        ///5900
        ///2512
        ///8622
        ///8669
        ///1183
        ///1397
        ///9986
        ///8019
        ///5483
        ///7962
        ///4402
        ///4310
        ///2482
        ///2186
        ///3439
        ///1873
        ///8374
        ///6343
        ///7177
        ///5253
        ///8561
        ///8024
        ///9014
        ///1311
        ///5
        ///8327
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NUMS_TEN_THOUSAND {
            get {
                return ResourceManager.GetString("NUMS_TEN_THOUSAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3
        ///3
        ///3
        ///5
        ///5
        ///6
        ///8
        ///9
        ///10
        ///11
        ///14
        ///15
        ///15
        ///16
        ///16
        ///18
        ///19
        ///19
        ///20
        ///21
        ///25
        ///26
        ///26
        ///26
        ///27
        ///29
        ///31
        ///32
        ///33
        ///33
        ///34
        ///37
        ///38
        ///38
        ///38
        ///39
        ///40
        ///42
        ///42
        ///45
        ///46
        ///46
        ///47
        ///47
        ///51
        ///51
        ///52
        ///54
        ///56
        ///57
        ///57
        ///57
        ///59
        ///60
        ///63
        ///63
        ///64
        ///65
        ///65
        ///66
        ///67
        ///67
        ///68
        ///68
        ///70
        ///72
        ///72
        ///73
        ///74
        ///75
        ///76
        ///81
        ///83
        ///83
        ///84
        ///85
        ///87
        ///89
        ///91
        ///93
        ///95
        ///96
        ///98
        ///98
        ///98
        ///99
        ///100
        ///100
        ///100
        ///100
        ///100
        ///103
        ///104
        ///104
        ///104
        ///105
        ///107
        ///108
        ///108
        ///109
        ///110
        ///110
        ///111
        ///111
        ///113
        ///116
        ///117
        ///118
        ///118
        ///120
        ///120
        ///120
        ///120
        ///122
        ///123
        ///123
        ///123
        ///125
        ///126
        ///126
        ///127
        ///1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NUMS_TEN_THOUSAND_SORTED {
            get {
                return ResourceManager.GetString("NUMS_TEN_THOUSAND_SORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10000
        ///9999
        ///9998
        ///9998
        ///9995
        ///9995
        ///9993
        ///9993
        ///9991
        ///9988
        ///9988
        ///9988
        ///9986
        ///9986
        ///9986
        ///9985
        ///9984
        ///9984
        ///9983
        ///9983
        ///9983
        ///9982
        ///9981
        ///9981
        ///9976
        ///9976
        ///9975
        ///9973
        ///9972
        ///9970
        ///9969
        ///9969
        ///9968
        ///9967
        ///9964
        ///9963
        ///9963
        ///9962
        ///9961
        ///9961
        ///9961
        ///9959
        ///9959
        ///9959
        ///9958
        ///9958
        ///9956
        ///9955
        ///9954
        ///9954
        ///9953
        ///9953
        ///9953
        ///9951
        ///9947
        ///9946
        ///9944
        ///9943
        ///9941
        ///9941
        ///9940
        ///9939
        ///9939
        ///9939
        ///9938
        ///9937
        ///9935
        ///9935
        ///9934
        ///9934
        ///9933
        ///9932
        ///9932
        ///9930
        ///9930
        ///9928
        ///9926
        ///9925
        ///9923
        ///9922
        ///9922
        ///9921
        ///9915
        ///9914
        ///9912
        ///9 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NUMS_TEN_THOUSAND_SORTED_REVERSE {
            get {
                return ResourceManager.GetString("NUMS_TEN_THOUSAND_SORTED_REVERSE", resourceCulture);
            }
        }
    }
}
